import type {
  Activity,
  ActivityTimestamps,
  ActivityEmoji,
  ActivityParty,
  ActivityAssets,
  ActivitySecrets,
  ActivityButtons,
  Identify,
  IdentifyConnectionProperties,
  GatewayEvent,
  GatewayResume,
  Heartbeat,
  PresenceUpdate,
} from './gateway';

export type {
  Activity,
  ActivityTimestamps,
  ActivityEmoji,
  ActivityParty,
  ActivityAssets,
  ActivitySecrets,
  ActivityButtons,
  Identify,
  IdentifyConnectionProperties,
  GatewayEvent,
  GatewayResume,
  Heartbeat,
  PresenceUpdate,
};
